apiVersion: v1
kind: Service
metadata:
  name: {{ include "notesnest.fullname" . }}-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "notesnest.app.labels" . | nindent 4 }}
  {{- with .Values.service.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
  - port: {{ .Values.service.app.port }}
    targetPort: {{ .Values.service.app.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "notesnest.app.selectorLabels" . | nindent 4 }} 