{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "notesnest.fullname" . }}-netpol
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "notesnest.app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "notesnest.app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  egress:
  # Allow egress to PostgreSQL
  - to:
    - podSelector:
        matchLabels:
          {{- include "notesnest.postgresql.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 5432
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow HTTPS for external API calls (if needed)
  - to: []
    ports:
    - protocol: TCP
      port: 443
  {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
---
# NetworkPolicy for PostgreSQL
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "notesnest.postgresql.fullname" . }}-netpol
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "notesnest.postgresql.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "notesnest.postgresql.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from NotesNest application
  - from:
    - podSelector:
        matchLabels:
          {{- include "notesnest.app.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 5432
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
{{- end }} 