{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notesnest.postgresql.serviceName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "notesnest.postgresql.labels" . | nindent 4 }}
  {{- with .Values.service.postgresql.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.postgresql.type }}
  ports:
  - port: {{ .Values.service.postgresql.port }}
    targetPort: {{ .Values.service.postgresql.targetPort }}
    protocol: TCP
    name: postgresql
  selector:
    {{- include "notesnest.postgresql.selectorLabels" . | nindent 4 }}
  clusterIP: None  # Headless service for StatefulSet
{{- end }} 