{{/* Validate that all required secrets are provided */}}
{{- include "notesnest.validateSecrets" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notesnest.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "notesnest.labels" . | nindent 4 }}
type: Opaque
data:
  # Application secrets
  DATABASE_URL: {{ include "notesnest.databaseUrl" . | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.app.secrets.jwtSecretKey | b64enc | quote }}
  
  # PostgreSQL secrets
  POSTGRES_USER: {{ .Values.app.secrets.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.app.secrets.postgresPassword | b64enc | quote }}
  POSTGRES_DB: {{ .Values.app.secrets.postgresDatabase | b64enc | quote }}
---
# Separate secret for PostgreSQL StatefulSet to avoid circular dependencies
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notesnest.postgresql.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "notesnest.postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.app.secrets.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.app.secrets.postgresPassword | b64enc | quote }}
  POSTGRES_DB: {{ .Values.app.secrets.postgresDatabase | b64enc | quote }} 